# build react app
FROM node:20.14.0-alpine as build

#working directory
WORKDIR /app

#copy packages.json
COPY package*.json ./

#install node dependencires
RUN npm install

#copy rest of the application
COPY . .

#build production app
RUN npm run build

# serve app with nginx

FROM nginx:1.21.0-alpine

COPY --from=build /app/build /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]