name: Build and Push Two Docker Images

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  # --- First Job: Build and push the API image ---
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set repo name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DHUB_USERN }}
          password: ${{ secrets.DHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: ./alzheimer_FastAPI  # Specifies the build context is the 'api' sub-directory
          file: ./alzheimer_FastAPI/dockerfile # Specifies the path to the API's Dockerfile
          push: true
          tags: ${{ secrets.DHUB_USERN }}/${{ env.REPO_NAME }}-backend:latest

  # --- Second Job: Build and push the WebApp image ---
  build-and-push-webapp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set repo name to lowercase
        run: echo "REPO_NAME=$(echo ${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DHUB_USERN }}
          password: ${{ secrets.DHUB_TOKEN }}

      - name: Build and push WebApp image
        uses: docker/build-push-action@v5
        with:
          context: ./react_base # Specifies the build context is the 'webapp' sub-directory
          file: ./react_base/dockerfile # Specifies the path to the WebApp's Dockerfile
          push: true
          tags: ${{ secrets.DHUB_USERN }}/${{ env.REPO_NAME }}-frontend:latest